using BlazzyMotion.Core.Models;
using System.Collections.Concurrent;

namespace BlazzyMotion.Core.Services;

/// <summary>
/// Central registry for BlazzyMotion type mappers.
/// </summary>
/// <remarks>
/// <para>
/// BzRegistry is the heart of the BlazzyMotion mapping system. It maintains
/// a thread-safe dictionary of mapping functions that convert user types
/// (decorated with [BzImage]) to <see cref="BzItem"/> instances.
/// </para>
/// <para>
/// <strong>How It Works:</strong>
/// <list type="number">
/// <item>Source Generator creates mapping functions at compile-time</item>
/// <item>[ModuleInitializer] registers them automatically at app startup</item>
/// <item>Components call <see cref="ToBzItems{T}"/> to convert user data</item>
/// </list>
/// </para>
/// <para>
/// <strong>Thread Safety:</strong>
/// All operations use <see cref="ConcurrentDictionary{TKey, TValue}"/> for
/// thread-safe access in multi-threaded scenarios (Blazor Server, etc.).
/// </para>
/// <para>
/// <strong>Performance:</strong>
/// <list type="bullet">
/// <item>Registration: O(1) - single dictionary insert</item>
/// <item>Lookup: O(1) - dictionary access</item>
/// <item>Mapping: O(n) - linear through items</item>
/// </list>
/// </para>
/// </remarks>
/// <example>
/// <code>
/// // Registration (done by Source Generator)
/// BzRegistry.Register&lt;Movie&gt;(movie => new BzItem
/// {
///     ImageUrl = movie.PosterUrl,
///     Title = movie.Title,
///     OriginalItem = movie
/// });
/// 
/// // Usage in component
/// var bzItems = BzRegistry.ToBzItems(movies);
/// </code>
/// </example>
public static class BzRegistry
{
    /// <summary>
    /// Thread-safe dictionary storing mapping functions.
    /// Key: Type (user's model type)
    /// Value: Func&lt;object, BzItem&gt; (mapper function)
    /// </summary>
    private static readonly ConcurrentDictionary<Type, Func<object, BzItem>> _mappers = new();

    /// <summary>
    /// Registers a mapping function for a specific type.
    /// </summary>
    /// <typeparam name="T">The type to register a mapper for</typeparam>
    /// <param name="mapper">Function that converts T to BzItem</param>
    /// <remarks>
    /// <para>
    /// This method is typically called by Source Generator-generated code
    /// in a [ModuleInitializer] method, ensuring automatic registration
    /// at application startup.
    /// </para>
    /// <para>
    /// If a mapper for the type already exists, it will be replaced.
    /// This allows for runtime overrides if needed.
    /// </para>
    /// </remarks>
    /// <example>
    /// <code>
    /// // Generated by Source Generator
    /// [ModuleInitializer]
    /// internal static void RegisterMovieMapper()
    /// {
    ///     BzRegistry.Register&lt;Movie&gt;(movie => new BzItem
    ///     {
    ///         ImageUrl = movie.PosterUrl,
    ///         Title = movie.Title,
    ///         OriginalItem = movie
    ///     });
    /// }
    /// </code>
    /// </example>
    public static void Register<T>(Func<T, BzItem> mapper) where T : class
    {
        // Wrap typed mapper in object-based mapper for storage
        _mappers[typeof(T)] = obj => mapper((T)obj);
    }

    /// <summary>
    /// Registers a mapping function using Type parameter (non-generic version).
    /// </summary>
    /// <param name="type">The type to register a mapper for</param>
    /// <param name="mapper">Function that converts object to BzItem</param>
    /// <remarks>
    /// Used when the type is not known at compile-time.
    /// Prefer the generic <see cref="Register{T}"/> when possible.
    /// </remarks>
    public static void Register(Type type, Func<object, BzItem> mapper)
    {
        _mappers[type] = mapper;
    }

    /// <summary>
    /// Converts a collection of items to BzItem instances.
    /// </summary>
    /// <typeparam name="T">The type of items in the collection</typeparam>
    /// <param name="items">Collection of items to convert</param>
    /// <returns>
    /// List of BzItem instances, or empty list if no mapper is registered
    /// </returns>
    /// <remarks>
    /// <para>
    /// This is the primary method used by BlazzyMotion components to
    /// convert user data to the internal BzItem format.
    /// </para>
    /// <para>
    /// <strong>Null Handling:</strong>
    /// <list type="bullet">
    /// <item>Null collection returns empty list</item>
    /// <item>Null items in collection are skipped</item>
    /// </list>
    /// </para>
    /// </remarks>
    /// <example>
    /// <code>
    /// // In BzCarousel component
    /// protected override void OnParametersSet()
    /// {
    ///     MappedItems = BzRegistry.ToBzItems(Items);
    /// }
    /// </code>
    /// </example>
    public static IReadOnlyList<BzItem> ToBzItems<T>(IEnumerable<T>? items) where T : class
    {
        if (items is null)
            return Array.Empty<BzItem>();

        if (!_mappers.TryGetValue(typeof(T), out var mapper))
        {
            // No mapper registered - return empty list
            // Component will use fallback template
            return Array.Empty<BzItem>();
        }

        var result = new List<BzItem>();

        foreach (var item in items)
        {
            if (item is null)
                continue;

            try
            {
                var bzItem = mapper(item);
                result.Add(bzItem);
            }
            catch
            {
                // Skip items that fail to map
                // This provides resilience against malformed data
            }
        }

        return result;
    }

    /// <summary>
    /// Converts a single item to BzItem.
    /// </summary>
    /// <typeparam name="T">The type of the item</typeparam>
    /// <param name="item">Item to convert</param>
    /// <returns>BzItem instance, or null if no mapper or item is null</returns>
    public static BzItem? ToBzItem<T>(T? item) where T : class
    {
        if (item is null)
            return null;

        if (!_mappers.TryGetValue(typeof(T), out var mapper))
            return null;

        try
        {
            return mapper(item);
        }
        catch
        {
            return null;
        }
    }

    /// <summary>
    /// Checks if a mapper is registered for the specified type.
    /// </summary>
    /// <typeparam name="T">The type to check</typeparam>
    /// <returns>True if a mapper exists for the type</returns>
    /// <example>
    /// <code>
    /// if (BzRegistry.HasMapper&lt;Movie&gt;())
    /// {
    ///     // Use automatic mapping
    /// }
    /// else
    /// {
    ///     // Use manual ItemTemplate
    /// }
    /// </code>
    /// </example>
    public static bool HasMapper<T>() where T : class
    {
        return _mappers.ContainsKey(typeof(T));
    }

    /// <summary>
    /// Checks if a mapper is registered for the specified type (non-generic).
    /// </summary>
    /// <param name="type">The type to check</param>
    /// <returns>True if a mapper exists for the type</returns>
    public static bool HasMapper(Type type)
    {
        return _mappers.ContainsKey(type);
    }

    /// <summary>
    /// Gets the count of registered mappers.
    /// </summary>
    /// <remarks>
    /// Useful for diagnostics and testing.
    /// </remarks>
    public static int MapperCount => _mappers.Count;

    /// <summary>
    /// Removes a registered mapper.
    /// </summary>
    /// <typeparam name="T">The type to unregister</typeparam>
    /// <returns>True if mapper was removed, false if not found</returns>
    /// <remarks>
    /// Primarily used for testing. Not typically needed in production.
    /// </remarks>
    public static bool Unregister<T>() where T : class
    {
        return _mappers.TryRemove(typeof(T), out _);
    }

    /// <summary>
    /// Clears all registered mappers.
    /// </summary>
    /// <remarks>
    /// <strong>Warning:</strong> Only use in testing scenarios.
    /// Clearing mappers in production will break all BlazzyMotion components.
    /// </remarks>
    public static void Clear()
    {
        _mappers.Clear();
    }
}